"""Orchestrates the full PD3 (Prøve i Dansk 3) extraction pipeline:
runs the reading/writing/speaking extractors, then emits the TypeScript
data files consumed by the app (src/data/pd3Reading.ts, pd3Writing.ts,
pd3Speaking.ts).

Usage: python3 scripts/generate_pd3_archive.py
Requires the source PDFs to be present under
source-papers/pd3_extracted/PD3 samples collection (2004-2024)/ (see README).
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(__file__)
JSON_DIR = os.path.join(HERE, 'pd3_json')
DATA_DIR = os.path.join(HERE, '..', 'src', 'data')


def run(script):
    print(f'--- running {script} ---')
    subprocess.run([sys.executable, os.path.join(HERE, script)], check=True)


def write_ts(json_name, ts_name, type_name, const_name, header):
    with open(os.path.join(JSON_DIR, json_name), encoding='utf-8') as f:
        data = json.load(f)
    js = json.dumps(data, ensure_ascii=False, indent=2)
    out_path = os.path.join(DATA_DIR, ts_name)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header + '\n')
        f.write(f"import type {{ {type_name} }} from '../types'\n\n")
        f.write(f'export const {const_name}: {type_name}[] = {js}\n')
    print(f'wrote {out_path} ({len(data)} items)')


def main():
    run('extract_pd3_reading.py')
    run('extract_pd3_writing.py')
    run('extract_pd3_speaking.py')

    write_ts('reading.json', 'pd3Reading.ts', 'PD3ReadingExam', 'pd3ReadingExams',
             '// PD3 (Prøve i Dansk 3) reading exams, auto-generated by\n'
             '// scripts/generate_pd3_archive.py from official past-exam PDFs\n'
             '// (2018-2024). Do not hand-edit; re-run the extraction pipeline instead.')
    write_ts('writing.json', 'pd3Writing.ts', 'PD3WritingExam', 'pd3WritingExams',
             '// PD3 (Prøve i Dansk 3) writing prompts, auto-generated by\n'
             '// scripts/generate_pd3_archive.py from official past-exam PDFs (2018-2024).\n'
             '// Do not hand-edit.')
    write_ts('speaking.json', 'pd3Speaking.ts', 'PD3SpeakingExam', 'pd3SpeakingExams',
             '// PD3 (Prøve i Dansk 3) speaking topics, auto-generated by\n'
             '// scripts/generate_pd3_archive.py from official past-exam PDFs (2018-2024).\n'
             '// Do not hand-edit.')


if __name__ == '__main__':
    main()
