// Hand-maintained helpers around the auto-generated PD3 (Prøve i Dansk 3)
// data files. Mirrors the reading.ts/readingArchive.ts split used for PD2:
// the pd3Reading/pd3Writing/pd3Speaking.ts files are regenerated by
// scripts/generate_pd3_archive.py, so any helper logic lives here instead.
import { pd3ReadingExams } from './pd3Reading'
import { pd3WritingExams } from './pd3Writing'
import { pd3SpeakingExams } from './pd3Speaking'

export { pd3ReadingExams, pd3WritingExams, pd3SpeakingExams }

export function getPD3ReadingExam(id: string) {
  return pd3ReadingExams.find((e) => e.id === id)
}

export function getPD3WritingExam(id: string) {
  return pd3WritingExams.find((e) => e.id === id)
}

export function getPD3SpeakingExam(id: string) {
  return pd3SpeakingExams.find((e) => e.id === id)
}
