// PD3 (Prøve i Dansk 3) speaking topics, auto-generated by
// scripts/generate_pd3_archive.py from official past-exam PDFs (2018-2024).
// Do not hand-edit.
import type { PD3SpeakingExam } from '../types'

export const pd3SpeakingExams: PD3SpeakingExam[] = [
  {
    "id": "pd3-2018-sommer",
    "exam": {
      "year": 2018,
      "season": "Sommer",
      "label": "Maj-juni 2018"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Frivilligt arbejde",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Frivilligt arbejde’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle studerende bruger tid på at lave frivilligt ulønnet arbejde, selvom de også har travlt med deres studier. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for studerendes fremtidige jobmuligheder, at de laver frivilligt arbejde?"
              },
              {
                "question": "Nogle danskere laver frivilligt ulønnet arbejde, når de er gået på pension. Hvor- for tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for pensionisters livskvalitet, at de laver frivilligt ulønnet arbejde?"
              }
            ],
            "secondQuestion": {
              "question": "På mange institutioner, fx plejehjem, skoler og museer, bruger man frivillige udover den professionelle arbejdskraft. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Hvilke typer af frivilligt arbejde mener du er mest nyttige for et velfærdssamfund som det danske? Hvorfor?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Sygefravær på arbejdspladsen",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Sygefravær på arbejdspladsen’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle mennesker går sommetider på arbejde, selvom de er forkølede. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for ens forhold til kollegerne, at man nogle gange går på arbejde, selvom man er forkølet?"
              },
              {
                "question": "Pædagoger og sygehjælpere har et højere sygefravær end ingeniører og konsulenter. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for ens forhold til kollegerne, at man har et højt sygefravær?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle virksomheder gør meget for at reducere de ansattes sygefravær. Virksomhederne tilbyder for eksempel gratis lægetjek og rådgivning om kost og motion. Hvilke fordele og ulemper mener du, der kan være ved, at de gør det?",
              "followUp": "Synes du, at det er i orden, at en virksomhed blander sig i de ansattes livsstil, eller bør ens livsstil være en privat sag? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Medier",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Medier’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Færre og færre danskere køber og læser avis. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der efter din mening være nogen problemer ved, at færre og færre danskere køber og læser avis? Hvorfor?/Hvorfor ikke?"
              },
              {
                "question": "Flere og flere danskere får deres nyheder gennem online-medier. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der efter din mening være nogen problemer ved, at flere og flere danskere får deres nyheder gennem online-medier? Hvorfor?/Hvorfor ikke?"
              }
            ],
            "secondQuestion": {
              "question": "Med blogs og andre online-medier er det i dag nemmere for almindelige mennesker at deltage i den offentlige debat. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Hvad tror du, det betyder for demokratiet, at det i dag er nemmere for almindelige mennesker at deltage i den offentlige debat? Hvorfor?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2018-vinter",
    "exam": {
      "year": 2018,
      "season": "Vinter",
      "label": "November-december 2018"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Arbejdsmiljø",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder til emnet ’Arbejdsmiljø’. Det ene viser en situation med en firmafest og det andet en situation med et kursus i teambuilding. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "På mange arbejdspladser har man sociale arrangementer som fx firmafester og skovture. Hvorfor tror du, man har det?",
                "followUp": "Hvad tror du, det betyder for medarbejdernes tilfredshed med deres arbejde, at man har sociale arrangementer?"
              },
              {
                "question": "På mange arbejdspladser kommer medarbejderne på kursus i teambuilding. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for medarbejdernes tilfredshed med deres arbejde, at de kommer på kursus i teambuilding?"
              }
            ],
            "secondQuestion": {
              "question": "I nogle virksomheder giver man en bonus – altså en ekstra sum penge – til medarbejdere, hvis de gør en særlig indsats for virksomheden. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Hvordan tror du, en bonus påvirker samarbejdet mellem medarbejderne? Og mellem medarbejderne og ledelsen?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Uddannelsesvalg",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder til emnet ’Uddannelsesvalg’. Det ene viser en situation med et studieophold i udlandet og det andet en situation med et studierelevant arbejde. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Nogle studerende vælger at studere et eller flere år på et universitet i udlandet. Hvorfor tror du, de vælger det?",
                "followUp": "Hvad tror du, det betyder for unges karrieremuligheder, at de har studeret et eller flere år på et universitet i udlandet?"
              },
              {
                "question": "Nogle unge vælger at arbejde et eller flere år, inden de begynder på en uddan- nelse? Hvorfor tror du, de vælger det?",
                "followUp": "Kan der være nogen problemer ved at arbejde i et eller flere år, inden man begynder på en uddannelse? Hvorfor?/Hvorfor ikke?"
              }
            ]
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Test i skolen",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder til emnet ’Test i skolen’. Det ene viser en situation med test i en skoleklasse og det andet en situation fra en afslutning på en folkeskole. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle mener, at det er vigtigt for børns læring, at de bliver testet i skolen fra de er helt små. Hvorfor tror du, de mener det?",
                "followUp": "Mener du, der kan være nogen problemer ved at teste børn i skolen? Hvorfor?/ Hvorfor ikke?"
              },
              {
                "question": "Nogle mener, at karakterer er for upræcise til at afgøre, om unge kan få en ung- domsuddannelse, fx komme i gymnasiet. Hvorfor tror du, de mener det?",
                "followUp": "Kan der være nogen problemer ved ikke at bruge karakterer, når man afgør om unge kan få en ungdomsuddannelse? Hvorfor?/Hvorfor ikke?"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2019-sommer",
    "exam": {
      "year": 2019,
      "season": "Sommer",
      "label": "Maj-juni 2019"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Transportformer",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er to billeder, der viser nogle situationer, der handler om emnet ’Transportformer’. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Der er flere og flere danskere, både unge og gamle, der køber en elcykel i stedet for en almindelig cykel. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved, at flere og flere danskere køber en elcykel i stedet for en almindelig cykel – fx for trafiksikkerheden eller sundheden? Hvorfor?/Hvorfor ikke?"
              },
              {
                "question": "Der er nogle, der mener, at der skal være mere plads til fodgængere og cyklister i de større byer. Hvorfor tror du, de mener det?",
                "followUp": "Mener du, der kan være nogen problemer ved at give mere plads til fodgængere og cyklister i de større byer? Hvorfor?/Hvorfor ikke?"
              }
            ],
            "secondQuestion": {
              "question": "Der er nogle, der mener, at der skal investeres i hurtigtog i hele landet. Hvilke fordele og ulemper mener du, der kan være ved det – fx for miljøet?",
              "followUp": "Tror du, det vil være bedre at investere i flere motorveje end i hurtigtog i hele landet? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Arbejde og arbejdstid",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, der viser nogle situationer, der handler om emnet ’Arbejde og arbejdstid’. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Nogle mennesker vælger i perioder at arbejde på deltid. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for folks karrieremuligheder, at de i perioder arbejder på deltid?"
              },
              {
                "question": "Nogle mennesker tjekker deres arbejdsmails om aftenen eller i weekenden. Hvor- for tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for folks karrieremuligheder, at de tjekker arbejdsmails om aftenen eller i weekenden?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle mennesker mener, at den almindelige arbejdstid skal sættes ned til 30 timer om ugen. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Tror du, at en 30 timers arbejdsuge vil betyde, at arbejdet bliver bedre fordelt mellem folk? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Kultur",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, der viser nogle situationer, der handler om emnet ’Kultur’. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Nogle danskere mener, at det skal være gratis at gå på museum. Hvorfor tror du, de mener det?",
                "followUp": "Hvad tror du, det betyder for folks interesse for kunst og kultur, at det ikke er gratis at gå på museum?"
              },
              {
                "question": "I Danmark er det gratis at bruge bibliotekerne. Hvorfor tror du, det er det?",
                "followUp": "Hvad tror du, det betyder for folks interesse for at læse, at det er gratis at låne bøger på bibliotekerne?"
              }
            ],
            "secondQuestion": {
              "question": "Flere kommuner bruger penge på dyre kulturhuse med kulturtilbud som fx teater, dans, musik og udstillinger. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, at en kommune skal bruge penge på kulturhuse, eller bør en kommune prioritere andre kulturtilbud eller andre områder som fx ældrepleje og uddannelse? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2019-vinter",
    "exam": {
      "year": 2019,
      "season": "Vinter",
      "label": "November-december 2019"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Køn og arbejde",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, der viser nogle situationer, der handler om emnet ’Køn og arbejde’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "I Danmark er der færre kvinder end mænd, der arbejder med it og finans. Hvor- for tror du, det er sådan?",
                "followUp": "Kan der efter din mening være nogen problemer ved, at der er færre kvinder end mænd, der arbejder med it og finans? Hvorfor?/Hvorfor ikke?"
              },
              {
                "question": "I Danmark er der færre mænd end kvinder, der arbejder med børn, fx som lærer eller pædagog. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for børnene, at der er færre mænd end kvinder, der er pædagoger eller lærere?"
              }
            ],
            "secondQuestion": {
              "question": "Man kunne lave regler for, hvor mange kvinder og mænd der kan optages på forskellige uddannelser, så der ikke er nogen uddannelser, hvor der næsten kun er kvin- der eller kun mænd. Hvilke fordele og ulemper mener du, der ville være ved det?",
              "followUp": "Synes du, det er vigtigt med en mere lige fordeling af kvinder og mænd i de forskellige brancher på arbejdsmarkedet? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Kostvaner og livsstil",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, der viser nogle situationer, der handler om emnet ’Kostvaner og livsstil’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "De fleste mennesker spiser fx slik eller chips eller drikker fx cola mellem hoved- måltiderne, selvom de godt ved, at det er usundt. Hvorfor tror du alligevel, at de gør det?",
                "followUp": "Kan der efter din mening være nogen problemer ved at spise fx slik eller chips eller drikke fx cola en gang imellem? Hvorfor?/Hvorfor ikke?"
              },
              {
                "question": "Nogle mennesker spiser ikke mad, der indeholder kød, æg eller mælkeprodukter. Hvorfor tror du ikke, de gør det?",
                "followUp": "Kan der efter din mening være nogen problemer ved ikke at spise mad, der indeholder kød, æg eller mælkeprodukter? Hvorfor?/Hvorfor ikke?"
              }
            ],
            "secondQuestion": {
              "question": "I medierne er det typisk sådan, at folk med succes er smukke og slanke og har sun- de kost- og motionsvaner. Hvilke fordele og ulemper mener du, der kan være ved, at de bliver fremstillet sådan?",
              "followUp": "Hvordan tror du, det påvirker især de unges selvtillid, at det typisk bliver fremstillet sådan, at det er smukke og slanke mennesker, der har succes?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Studieboliger",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, der viser nogle situationer, der handler om emnet ’Studieboliger’. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Mange studerende vil gerne studere i Aarhus eller København, selvom der er lange ventelister til studieboliger i de to byer. Hvorfor tror du alligevel, de gerne vil det?",
                "followUp": "Hvad tror du, det betyder for, hvor og hvordan de unge bor, at der er lange ventelister til studieboliger?"
              },
              {
                "question": "Mange forældre køber en lejlighed til deres børn, når børnene starter på en uddannelse. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for de unges studieliv, at de kan bo i egen lejlighed?"
              }
            ],
            "secondQuestion": {
              "question": "I de store universitetsbyer kan man vælge at bygge flere studieboliger til studerende i stedet for fx boliger til ældre. Hvilke fordele og ulemper mener du, der kan være ved det for de store universitetsbyer?",
              "followUp": "Synes du, at det er studiebyernes ansvar at sørge for, at der er billige studieboliger og kollegier til alle studerende? Hvorfor?/Hvorfor ikke?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2020-sommer",
    "exam": {
      "year": 2020,
      "season": "Sommer",
      "label": "Maj-juni 2020"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Børns tid online",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Børns tid online’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "På nogle skoler må elever ikke bruge deres mobiltelefon i skoletiden. Hvorfor tror du, det er sådan?",
                "followUp": ""
              },
              {
                "question": "Nogle børn vil hellere spille computerspil end lege udenfor sammen med deres venner. Hvorfor tror du, det er sådan?",
                "followUp": ""
              }
            ],
            "secondQuestion": {
              "question": "Nogle børn og unge bruger næsten hele deres sociale liv online, fx på sociale medier. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": ""
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Det offentlige sundhedsvæsen",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Det offentlige sundhedsvæsen’. Du har nu ca. 10 sekunder til at kigge på billederne",
            "firstQuestions": [
              {
                "question": "Der er nogle, der mener, at det ikke skal være helt gratis at gå til læge. De mener, at det er en god idé at indføre et gebyr ved lægebesøg. Hvorfor tror du, de mener det?",
                "followUp": "Mener du, der kan være nogen problemer ved at indføre et gebyr ved lægebesøg? Hvorfor?/Hvorfor ikke?"
              },
              {
                "question": "Der er nogle, der vælger at betale for behandling på et privathospital. Hvorfor tror du, de vælger det?",
                "followUp": "Mener du, der kan være nogen problemer ved, at nogle ikke har råd til at betale for behandling på et privathospital? Hvorfor?/Hvorfor ikke?"
              }
            ],
            "secondQuestion": {
              "question": "Der bliver færre men større hospitaler i Danmark. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": ""
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Arbejde og sprog",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Arbejde og sprog’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle firmaer betaler for danskkurser til deres udenlandske medarbejdere, selvom virksomhedssproget er engelsk. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for det kollegiale samvær på arbejdspladsen, at de udenlandske medarbejdere lærer dansk?"
              },
              {
                "question": "Der er flere og flere uddannelser i Danmark, hvor studiesproget er engelsk. Hvor- for tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved, at studiesproget på flere og flere uddannelser i Danmark er engelsk?"
              }
            ],
            "secondQuestion": {
              "question": "Udlændinge kan ofte arbejde i Danmark uden at kunne tale dansk, hvis de kan tale engelsk. Hvilke fordele og ulemper mener du, der kan være ved det for det danske samfund?",
              "followUp": "Hvad tror du, det betyder for udenlandske medarbejderes muligheder for at blive integreret i det danske samfund, at de kan klare sig på engelsk?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2020-vinter",
    "exam": {
      "year": 2020,
      "season": "Vinter",
      "label": "November-december 2020"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Arbejdsliv og familieliv",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Arbejdsliv og familieliv’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Der er nogle, der venter med at få børn, til de er sidst i 30’erne. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved at vente med at få børn, til man er sidst i 30’erne?"
              },
              {
                "question": "Der er nogle, der vælger at få børn, mens de er studerende. Hvorfor tror du, de vælger det?",
                "followUp": "Mener du, der kan være nogen problemer ved at få børn, mens man er studerende?"
              }
            ],
            "secondQuestion": {
              "question": "Det er ofte moren, der holder den længste forældreorlov. Hvilke fordele og ulemper mener du, der kan være ved det for moren i forhold til familie og arbejde?",
              "followUp": "Hvad tror du, det betyder for ligestillingen i samfundet, at moren ofte holder den længste orlov?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Frivilligt arbejde",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Frivilligt arbejde’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Mange af dem, der arbejder frivilligt, er forældre med hjemmeboende børn. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for familielivet, at mange af dem, der arbejder frivilligt, er forældre med hjemmeboende børn?"
              },
              {
                "question": "Mange af dem, der arbejder frivilligt er pensionister. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for pensionisters livskvalitet, at de arbejder frivilligt?"
              }
            ],
            "secondQuestion": {
              "question": "Kommunerne gør mere og mere brug af frivillig arbejdskraft inden for fx ældrepleje og sundhed. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Hvad mener du om, at kommuner gør brug af frivillig arbejdskraft for at spare penge på løn til professionelle?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Unge og sundhed",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Unge og sundhed’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Der er nogle unge, der ryger, selvom de godt ved, at det er usundt. Hvorfor tror du alligevel, de gør det?",
                "followUp": "Hvad tror du, det betyder for de unges sociale relationer, at de ryger?"
              },
              {
                "question": "Nogle unge går i fitnesscenter hver dag og går meget op i, hvad de spiser og drik- ker. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der være nogen problemer ved at gå i fitnesscenter hver dag og gå meget op i, hvad man spiser og drikker?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle mener, at samfundet bør prøve at påvirke unges usunde livsstil, fx ved at sætte prisen på cigaretter og alkohol markant op. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Hvad tror du, det vil betyde for sundheden og livskvaliteten for lavtlønnede borgere, hvis priserne på cigaretter og alkohol bliver sat markant op?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2021-sommer",
    "exam": {
      "year": 2021,
      "season": "Sommer",
      "label": "Maj-juni 2021"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Jobsøgning",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Jobsøgning’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle nyuddannede kan have svært ved at finde det første job. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, erfaring fra fx et studiejob eller praktik kan betyde for de nyuddannedes muligheder for at finde et job?"
              },
              {
                "question": "Jobsøgende over 55 år kan have svært ved at finde et nyt job, selvom de har mange års erfaring. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved, at nogle arbejdsgivere fravælger jobsøgende over 55 år med mange års erfaring?"
              }
            ],
            "secondQuestion": {
              "question": "De fleste jobsøgende i Danmark kan modtage økonomisk hjælp som fx dagpenge eller kontanthjælp, mens de søger job. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Hvad tror du, den økonomiske hjælp kan betyde for de arbejdsløses jobsøgning?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Klimabevidsthed",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Klimabevidsthed’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Der er nogle, der vælger ikke at flyve, når de rejser på ferie. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for en families rejsevaner, at de fravælger flyrejser?"
              },
              {
                "question": "Der er nogle, der køber deres tøj og andre ting i genbrugsbutikker. Hvorfor tror du, de gør det?",
                "followUp": "Hvad tror du, det betyder for miljøet, at der er nogle, der køber deres tøj og andre ting i genbrugsbutikker?"
              }
            ],
            "secondQuestion": {
              "question": "Der er nogle, der mener, at Danmark i løbet af de næste 10 år skal skifte til at bruge 100 % grøn energi. Hvilke fordele og ulemper mener du, der kan være ved det for danske virksomheder?",
              "followUp": "Tror du, det vil betyde noget for den enkelte borgers livsstil, hvis Danmark i løbet af de næste 10 år skal skifte til at bruge 100 % grøn energi?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Unge under 18 og kriminalitet",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet ’Unge under 18 og kriminalitet’. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "10-14-årige børn begår flere butikstyverier end voksne. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for de 10-14-årige børns risiko for at blive kriminelle som voksne, at de begår butikstyverier som børn?"
              },
              {
                "question": "Unge mænd under 18 år begår generelt mere kriminalitet end unge kvinder under 18 år. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, man kan gøre for at få færre unge mænd til at begå kriminalitet?"
              }
            ],
            "secondQuestion": {
              "question": "Unge under 15 år kan ikke komme i fængsel, selvom de begår alvorlig kriminalitet som fx tyveri og vold. Hvilke fordele og ulemper mener du, der kan være ved det i forhold til kriminaliteten i samfundet?",
              "followUp": "Hvad tror du, det betyder for kriminelle unges muligheder for at komme ud af kriminaliteten, at de ikke kommer i fængsel, hvor der også er voksne indsatte?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2021-vinter",
    "exam": {
      "year": 2021,
      "season": "Vinter",
      "label": "November-december 2021"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Klima og forbrug",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet Klima og forbrug. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Der er mange, der smider mad ud, selvom det godt kan spises. Hvorfor tror du, de gør det?",
                "followUp": "Hvad mener du, den enkelte kan gøre for at undgå madspild?"
              },
              {
                "question": "Der er nogle, der køber en ny smartphone, selvom den gamle stadig virker. Hvorfor tror du, de gør det? Forslag til opfølgende spørgsmål:*",
                "followUp": "Mener du, der kan være nogen problemer ved, at man køber en ny smartphone, selvom den gamle stadig virker?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle mener, der skal være højere afgifter på fx kød, flyrejser, elektronik og andre produkter, der er forbundet med et stort CO2-udslip. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Hvad tror du, højere afgifter vil betyde for forbruget blandt højtlønnede og lavtlønnede?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Transportvaner",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet Transportvaner. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "I Danmark er der mange, der bruger cyklen til transport, fx til og fra arbejde. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for trafiksikkerheden i byerne, at der er mange, der bruger cyklen til transport?"
              },
              {
                "question": "Der er mange, der vælger bilen til transport, fx til og fra arbejde, selvom der i Danmark er gode muligheder for offentlig transport. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der efter din mening være nogen problemer ved, at der er mange, der vælger bilen til transport?"
              }
            ],
            "secondQuestion": {
              "question": "Der er nogle, der mener, at der skal være mere og billigere offentlig transport. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Hvad tror du, det vil betyde for miljøet, hvis den offentlige transport bliver billigere?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Uddannelsesvalg",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet Uddannelsesvalg. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "På mange uddannelser er der en begrænsning på, hvor mange studerende der bliver optaget. Hvorfor tror du, der er det?",
                "followUp": "Mener du, der kan være nogen problemer ved, at der på mange uddannelser er en begrænsning på, hvor mange studerende der bliver optaget?"
              },
              {
                "question": "Der er ofte ledige studiepladser på uddannelserne til lærer og pædagog, selvom der næsten er jobgaranti. Hvorfor tror du, det er sådan? Forslag til opfølgende spørgsmål:*",
                "followUp": "Mener du, der kan være nogen problemer ved, at der er ledige studiepladser på uddannelserne til lærer og pædagog."
              }
            ],
            "secondQuestion": {
              "question": "Der er nogle unge, der tager et eller to års pause efter gymnasiet, før de vælger uddannelse. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Hvad tror du, det betyder for de unges uddannelsesvalg, at de har holdt et eller to års pause?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2022-vinter",
    "exam": {
      "year": 2022,
      "season": "Vinter",
      "label": "November-december 2022"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "At gå i gymnasiet",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet At gå i gymnasiet. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nogle gymnasieelever er kun tilfredse med sig selv, hvis de får topkarakterer i alle fag. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der være nogen problemer ved, at man kun er tilfreds med sig selv, hvis man får topkarakterer i alle fag?"
              },
              {
                "question": "Nogle gymnasielever vælger at have et fritidsjob, mens de går i gymnasiet. Hvor- for tror du, de vælger det?",
                "followUp": "Kan der være nogen problemer ved at have et fritidsjob, mens man går i gymnasiet?"
              }
            ],
            "secondQuestion": {
              "question": "Der er flere unge, der tager en gymnasieuddannelse, end unge, der tager en erhvervsuddannelse som fx elektriker, tømrer eller murer. Hvilke fordele og ulemper mener du, der kan være ved det for det danske samfund?",
              "followUp": "Hvorfor tror du, mange foretrækker en gymnasieuddannelse, selvom der mangler folk med en erhvervsuddannelse i Danmark?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Tilflytning til de større byer",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet Tilflytning til de større byer. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Mange unge fra mindre byer flytter til en af de større byer i Danmark, når de flytter hjemmefra. Hvorfor tror du, de gør det?",
                "followUp": "Mener du, der kan være nogen problemer ved, at mange unge fra mindre byer flytter til en af de større byer i Danmark, når de flytter hjemmefra?"
              },
              {
                "question": "Der er nogen, der vælger at flytte fra en landsby til en større by, når de bliver ældre. Hvorfor tror du, de vælger det?",
                "followUp": "Hvad tror du, det betyder for ældres livskvalitet at bo i en større by i stedet for en landsby?"
              }
            ],
            "secondQuestion": {
              "question": "Generelt er der i Danmark en tendens til, at flere og flere flytter fra de mindre byer til de større byer. Hvilke fordele og ulemper mener du, der kan være ved det for de små lokalsamfund og for de større byer?",
              "followUp": "Mener du, det offentlige skal støtte små lokalsamfund, fx ved at sikre, at der er skoler og indkøbsmuligheder?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "At skifte job",
        "situations": [
          {
            "label": "Situation",
            "description": "Her er der to billeder, som viser nogle situationer, der handler om emnet At skifte job. Du har nu ca. 10 sekunder til at kigge på billederne.",
            "firstQuestions": [
              {
                "question": "Nyuddannede skifter oftere job end folk med mange års erfaring. Hvorfor tror du, det er sådan?",
                "followUp": "Hvad tror du, det betyder for de nyuddannedes arbejdsliv, at de oftere skifter job?"
              },
              {
                "question": "Der er nogen, der vælger at skifte til et nyt job på samme arbejdsplads. Hvorfor tror du, de vælger det?",
                "followUp": "Mener du, der kan være nogen problemer ved at skifte til et nyt job på samme arbejdsplads?"
              }
            ],
            "secondQuestion": {
              "question": "I Danmark er der generelt flere, der skifter job i løbet af deres arbejdsliv end i mange andre lande. Hvilke fordele og ulemper mener du, der kan være ved det for de danske virksomheder?",
              "followUp": "Tror du, det er vigtigere for en virksomhed at få nye medarbejdere med nye ideer end at beholde erfarne medarbejdere?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2023-sommer",
    "exam": {
      "year": 2023,
      "season": "Sommer",
      "label": "Maj-juni 2023"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Brug af sociale medier",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en ung mand, der sælger to ure via de sociale medier.",
            "firstQuestions": [
              {
                "question": "Flere og flere køber og sælger produkter via sociale medier. Hvorfor tror du, de gør det?",
                "followUp": "Mener du, der kan være nogen problemer ved at købe og sælge produkter via sociale medier?"
              }
            ],
            "secondQuestion": {
              "question": "I dag læser mange deres nyheder på de sociale medier. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, at de sociale medier har en positiv eller negativ betydning for demokratiet?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en ung kvinde, der lægger personlige billeder ud på sociale medier.",
            "firstQuestions": [
              {
                "question": "Mange mennesker lægger private og personlige billeder ud på de sociale medier. Hvorfor tror du, de gør det?",
                "followUp": "Mener du, der kan være nogen problemer ved at lægge private og personlige billeder ud på de sociale medier?"
              }
            ],
            "secondQuestion": {
              "question": "I dag læser mange deres nyheder på de sociale medier. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, at de sociale medier har en positiv eller negativ betydning for demokratiet?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Studerende og økonomi",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser nogle unge kvindelige studerende, der har et studiejob på en bar.",
            "firstQuestions": [
              {
                "question": "Nogle studerende vælger at arbejde ved siden af deres studier. Hvorfor tror du, de gør det?",
                "followUp": "Kan der være nogen problemer ved, at studerende arbejder ved siden af deres studier?"
              }
            ],
            "secondQuestion": {
              "question": "I Danmark er det normalt gratis at tage en uddannelse. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, at alle uddannelser skal være gratis, selvom det koster mange penge for samfundet?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en ung mandlig studerende, der har taget studielån for at betale sine udgifter.",
            "firstQuestions": [
              {
                "question": "Nogle studerende vælger også at låne penge, selvom de allerede modtager SU. Hvorfor tror du, de gør det?",
                "followUp": "Mener du, det er rimeligt, at studerende bruger penge på fx ferier eller at gå i byen?"
              }
            ],
            "secondQuestion": {
              "question": "I Danmark er det normalt gratis at tage en uddannelse. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, at alle uddannelser skal være gratis, selvom det koster mange penge for samfundet?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Jobsøgning og ledighed",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en ung og en ældre mand, der søger job. Den unge mand er til en jobsamtale, og den ældre er mødt op på jobcentret.",
            "firstQuestions": [
              {
                "question": "Arbejdsløse under 25 år kommer generelt hurtigere i job end arbejdsløse over 60 år. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, at arbejdsløse, der har en uddannelse, bør søge et ufaglært arbejde for hurtigere at komme i arbejde igen?"
              }
            ],
            "secondQuestion": {
              "question": "I Danmark kan man få økonomisk støtte, hvis man er arbejdsløs. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Synes du, der bør være en grænse for, hvor længe arbejdsløse kan få økonomisk støtte fra det offentlige?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en arbejdsløs mand, der har fundet et job, der ligger langt væk fra, hvor han bor.",
            "firstQuestions": [
              {
                "question": "Nogle søger kun job tæt på, hvor de bor, selvom de har svært ved at finde et job. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved, at nogle kun søger job tæt på, hvor de bor?"
              }
            ],
            "secondQuestion": {
              "question": "I Danmark kan man få økonomisk støtte, hvis man er arbejdsløs. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Synes du, der bør være en grænse for, hvor længe arbejdsløse kan få økonomisk støtte fra det offentlige?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2023-vinter",
    "exam": {
      "year": 2023,
      "season": "Vinter",
      "label": "November-december 2023"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "At søge læge",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en mand, der ikke har kontaktet lægen, selvom han har meget ondt.",
            "firstQuestions": [
              {
                "question": "Der er en tendens til, at mænd venter længere end kvinder med at gå til læge, selvom de ikke føler sig helt raske. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved, at man venter lidt med at gå til læge, selvom man ikke føler sig helt rask?"
              }
            ],
            "secondQuestion": {
              "question": "Alle har ret til gratis behandling på et hospital, men man har ofte mulighed for at blive behandlet hurtigere på et privathospital, hvis man selv kan og vil betale for det. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, det er rimeligt, at folk kan blive behandlet hurtigere, hvis de kan og vil betale for det?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en kvinde, der har en videokonsultation med sin læge, fordi hun har noget eksem på armen.",
            "firstQuestions": [
              {
                "question": "Flere og flere bruger videokonsultation i stedet for at møde fysisk op hos lægen. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved at bruge videokonsultation i stedet for at møde fysisk op hos lægen?"
              }
            ],
            "secondQuestion": {
              "question": "Alle har ret til gratis behandling på et hospital, men man har ofte mulighed for at blive behandlet hurtigere på et privathospital, hvis man selv kan og vil betale for det. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, det er rimeligt, at folk kan blive behandlet hurtigere, hvis de kan og vil betale for det?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Arbejde og alder",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en ældre kvinde, der arbejder som lægesekretær.",
            "firstQuestions": [
              {
                "question": "Nogle bliver ved med at arbejde, selvom de har mulighed for at gå på pension. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der være nogen problemer ved at blive ved med at arbejde, selvom man har mulighed for at gå på pension?"
              }
            ],
            "secondQuestion": {
              "question": "Folkepensionsalderen er den samme for alle, der er født det samme år. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, pensionsalderen bør være kortere for faggrupper, der har hårdt fysisk arbejde – som fx murere og rengøringsassistenter?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en ung mand, der arbejder som lagermedarbejder.",
            "firstQuestions": [
              {
                "question": "Nogle unge får ikke en uddannelse efter folkeskolen, men kommer direkte ud på arbejdsmarkedet. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der være nogen problemer ved, at nogle unge ikke får en uddannelse efter folkeskolen, men kommer direkte ud på arbejdsmarkedet?"
              }
            ],
            "secondQuestion": {
              "question": "Folkepensionsalderen er den samme for alle, der er født det samme år. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, pensionsalderen bør være kortere for faggrupper, der har hårdt fysisk arbejde – som fx murere og rengøringsassistenter?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Klima og livsstil",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en familie, hvor de to ældste piger har valgt ikke at spise kød.",
            "firstQuestions": [
              {
                "question": "Antallet af vegetarer og veganere er steget de senere år. Hvorfor tror du, det er sådan?",
                "followUp": "Mener du, der kan være nogen problemer ved at være vegetar eller veganer?"
              }
            ],
            "secondQuestion": {
              "question": "Det er især unge, der har fokus på at leve klimavenligt. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, der kan være nogen problemer ved at prioritere klima frem for velfærd?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en familie, der er på vej på ferie.",
            "firstQuestions": [
              {
                "question": "Nogle rejser meget med fly, selvom de godt ved, at det er skadeligt for klimaet. Hvorfor tror du, de alligevel gør det?",
                "followUp": "Tror du, folk også vil rejse meget med fly i fremtiden?"
              }
            ],
            "secondQuestion": {
              "question": "Det er især unge, der har fokus på at leve klimavenligt. Hvilke fordele og ulemper mener du, der kan være ved det?",
              "followUp": "Mener du, der kan være nogen problemer ved at prioritere klima frem for velfærd?"
            }
          }
        ]
      }
    ]
  },
  {
    "id": "pd3-2024-sommer",
    "exam": {
      "year": 2024,
      "season": "Sommer",
      "label": "Maj-juni 2024"
    },
    "topics": [
      {
        "id": "topic-a",
        "letter": "A",
        "title": "Støtte til kultur",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en familie, der er på vej ind på et kunstmuseum, hvor der er gratis adgang for børn.",
            "firstQuestions": [
              {
                "question": "Børn kan ofte få gratis adgang eller rabat til kulturinstitutioner som fx museer eller teatre. Hvorfor tror du, de kan det?",
                "followUp": "Synes du, det er en god idé at tage børn med på museum?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle kommuner vælger at bruge mange penge på store, internationale sportsbegivenheder som europamesterskaber og verdensmesterskaber. Hvilke fordele og ulemper mener du, der kan være ved det for kommunerne?",
              "followUp": "Mener du, at en kommune hellere skulle prioritere at bruge penge på andre områder end store, internationale sportsbegivenheder – fx børnepasning eller ældrepleje?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en biograf, der reklamerer for en ny dansk film.",
            "firstQuestions": [
              {
                "question": "I Danmark kan kunstnere få støtte af staten til at lave film. Hvorfor tror du, de kan det?",
                "followUp": "Synes du, det er vigtigt, at staten støtter danske film?"
              }
            ],
            "secondQuestion": {
              "question": "Nogle kommuner vælger at bruge mange penge på store, internationale sportsbegivenheder som europamesterskaber og verdensmesterskaber. Hvilke fordele og ulemper mener du, der kan være ved det for kommunerne?",
              "followUp": "Mener du, at en kommune hellere skulle prioritere at bruge penge på andre områder end store, internationale sportsbegivenheder – fx børnepasning eller ældrepleje?"
            }
          }
        ]
      },
      {
        "id": "topic-b",
        "letter": "B",
        "title": "Mangel på arbejdskraft",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en sygeplejerske, der har ansvar for mange patienter og har travlt.",
            "firstQuestions": [
              {
                "question": "Der mangler arbejdskraft i sundhedssektoren, fx sygeplejersker og social- og sundhedsassistenter. Hvorfor tror du, der gør det?",
                "followUp": "Hvilke problemer mener du, der kan være ved, at der mangler sygeplejersker og social- og sundhedsassistenter?"
              }
            ],
            "secondQuestion": {
              "question": "Ved mangel på arbejdskraft kan man fra politisk side vælge at gøre det nemmere for virksomheder at rekruttere udenlandsk arbejdskraft. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, det er i orden at rekruttere udenlandsk arbejdskraft, selvom der er borgere i Danmark, der er arbejdsløse?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en byggeplads, hvor arbejdet endnu ikke er gået i gang.",
            "firstQuestions": [
              {
                "question": "Der mangler arbejdskraft i byggebranchen, fx tømrere og jord- og betonarbejdere. Hvorfor tror du, der gør det?",
                "followUp": ""
              }
            ],
            "secondQuestion": {
              "question": "Ved mangel på arbejdskraft kan man fra politisk side vælge at gøre det nemmere for virksomheder at rekruttere udenlandsk arbejdskraft. Hvilke fordele og ulemper mener du, der kan være ved det for samfundet?",
              "followUp": "Mener du, det er i orden at rekruttere udenlandsk arbejdskraft, selvom der er borgere i Danmark, der er arbejdsløse?"
            }
          }
        ]
      },
      {
        "id": "topic-c",
        "letter": "C",
        "title": "Pædagogik i folkeskolen",
        "situations": [
          {
            "label": "Situation A",
            "description": "Situation A viser en folkeskoleklasse, hvor flere af børnene er urolige og uopmærksomme.",
            "firstQuestions": [
              {
                "question": "I nogle klasser i folkeskolen er der meget uro. Hvorfor tror du, der er det?",
                "followUp": "Hvad mener du, lærerne kan gøre for at begrænse uroen i klasserne?"
              }
            ],
            "secondQuestion": {
              "question": "I folkeskolen går eleverne typisk i samme klasse i de fleste fag, selvom de har forskelligt fagligt niveau. Hvilke fordele og ulemper mener du, der kan være ved det i forhold til børnenes faglige og sociale udvikling?",
              "followUp": "Hvad mener du, det betyder for samfundet, at børn går i samme klasse, selvom de har forskelligt fagligt niveau?"
            }
          },
          {
            "label": "Situation B",
            "description": "Situation B viser en klasse, hvor eleverne sidder og arbejder sammen om en opgave.",
            "firstQuestions": [
              {
                "question": "Eleverne får ikke karakterer i de første klasser i folkeskolen. Hvorfor tror du, det er sådan?",
                "followUp": "Kan der være nogen problemer ved, at der ikke gives karakterer i de første klasser i folkeskolen?"
              }
            ],
            "secondQuestion": {
              "question": "I folkeskolen går eleverne typisk i samme klasse i de fleste fag, selvom de har forskelligt fagligt niveau. Hvilke fordele og ulemper mener du, der kan være ved det i forhold til børnenes faglige og sociale udvikling?",
              "followUp": "Hvad mener du, det betyder for samfundet, at børn går i samme klasse, selvom de har forskelligt fagligt niveau?"
            }
          }
        ]
      }
    ]
  }
]
