// PD3 (Prøve i Dansk 3) writing prompts, auto-generated by
// scripts/generate_pd3_archive.py from official past-exam PDFs (2018-2024).
// Do not hand-edit.
import type { PD3WritingExam } from '../types'

export const pd3WritingExams: PD3WritingExam[] = [
  {
    "id": "pd3-2018-sommer",
    "exam": {
      "year": 2018,
      "season": "Sommer",
      "label": "Maj-juni 2018"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din ven Sofie, der bor i en lejlighed, hvor huslejen er steget. Hun overvejer\nderfor at leje et værelse ud for at få råd til at blive boende.\n\nNu har alle lejlighederne i vores opgang fået fine badeværelser og nye\nkøkkener. Det er dejligt med nyt bad og køkken, men desværre er huslejen\nsteget, så jeg overvejer at leje mit lille arbejdsværelse ud til en studerende –\nhvis det altså ikke er for besværligt. Hvordan var det for dig, da du havde en\nlejer boende?\nJeg kan selvfølgelig også prøve at finde en mindre lejlighed med en billigere\nhusleje. Synes du, det er en bedre idé?\nJeg håber, I er glade for jeres nye hus. Det må være dejligt med en have\nog masser af plads. Men hvordan er det at have fået langt til arbejde? Jeg\ntænker faktisk selv på at flytte udenfor byen på et tidspunkt, men foreløbig\npasser det mig godt at bo her.\nDet må også være godt for børnene med egne værelser, nye omgivelser og\nnye venner. Hvordan har de haft det med at flytte?...",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at Sofie kommer på besøg hos jer."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Forældre for første gang",
        "situation": "Delprøve 2A",
        "context": "Gennemsnitsalderen for førstegangsfødende kvinder og førstegangsfædre\ni perioden 1988-2015.\nfædre\når\når\når\når\når\når\når\når\nKilde: Danmarks statistik",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til den udvikling, diagrammet viser.",
          "Vurder fordele og ulemper ved at vente med at få børn, til man er i slutningen af 30’erne, fordi man har ambitioner om at gøre karriere, inden man får børn. redlA"
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Digitalisering",
        "situation": "Delprøve 2B",
        "context": "Samfundet bliver mere og mere digitaliseret, og der er forskellige opfattelser af, hvilke konsekvenser det har\nfor borgerne.\nHer er der nogle synspunkter:\n• D igitalisering gør det let og hurtigt at komme i kontakt med offentlige myndigheder.\n• D igitalisering gør det praktisk og enkelt at overføre eller modtage penge.\n• D igitalisering i folkeskolen gør det lettere for forældre at følge med i børnenes skolegang.\n• D igitalisering i sundhedssektoren medfører, at personalet har mindre kontakt med patienterne.\n• D igitalisering og selvbetjening i det offentlige stiller ældre borgere dårligere.\n• D igitalisering gør det nemmere for it-kriminelle at stjæle og bruge personlige oplysninger.",
        "bullets": [
          "Fortæl kort om dine egne erfaringer med digitalisering.",
          "Kommentér et eller to af synspunkterne fra listen.",
          "V urdér, hvilken betydning øget digitalisering vil få for borgernes trivsel i fremtiden. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2018-vinter",
    "exam": {
      "year": 2018,
      "season": "Vinter",
      "label": "November-december 2018"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din ven Anne. Hun bor i Aarhus og blev færdig med sin uddannelse som\narkitekt for tre måneder siden, men har endnu ikke fundet et arbejde.\n\nJeg ved godt, at tre måneder måske ikke er så lang tid, men jeg er ved at blive\nutålmodig. Jeg vil virkelig gerne finde et arbejde snart! Jeg har sendt en masse\nansøgninger, men det er ikke let at få et job, når man er nyuddannet. Faktisk har\njeg overvejet at tilbyde min arbejdskraft gratis til et arkitektfirma i en periode, så\njeg kan få noget erfaring. Hvad synes du om den ide?\nEn anden mulighed er at søge arbejde i en anden by, men jeg har jo alle mine ven-\nner her i Aarhus, og det er dejligt at have familien tæt på. Hvordan tror du, at det\nvil være at bo i en by, hvor jeg slet ikke har noget netværk?\nHvis der går lang tid, før jeg finder noget, kunne jeg måske søge arbejde inden for\net andet fagområde, hvor jeg også kan bruge mine kvalifikationer. Men det er jo\nmin drøm at arbejde som arkitekt, så jeg ved ikke rigtig. Tror du, det er en god ide?\nDu har jo forresten selv lige fået nyt job. Hvorfor var det nu, du søgte nyt job?",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Medier",
        "situation": "Delprøve 2A",
        "context": "Nyhedskilder, Danmark\n90%\n80%\n70%\n60%\n50%\n40%\n30%\n20%\n10%\n0%\n2013 2014 2015 2016\nTV Aviser Sociale medier\nKilde: http://www.digitalnewsreport.org/survey/2016/denmark-2016/",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til en eller flere af de forskelle, diagrammet viser.",
          "Vurder fordele og ulemper ved, at nyhedsformidlingen i stadig højere grad foregår via sociale medier."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Kvindelige topledere",
        "situation": "Delprøve 2B",
        "context": "Selvom der er en høj grad af ligestilling mellem kvinder og mænd i Danmark, så er der langt flere\nmandlige end kvindelige topledere. Det er der forskellige årsager til.\nNyhedskilder, Danmark\nMulige årsager:\n• Kvinder prioriterer i højere grad familien end karrieren.\n• Mænd er bedre til at træffe upopulære beslutninger end kvinder.\n• Kvinder lægger ikke så meget vægt på et job med status som mænd.\n• Mænd er mere fokuserede og målrettede end kvinder.\n• Kvinder er ikke så gode til at fremhæve egne kvalifikationer.\n• Mandlige topledere foretrækker at ansætte andre mænd.",
        "bullets": [
          "Fortæl kort om kønsfordelingen i ledelsen på en arbejdsplads, du kender.",
          "Kommentér et eller to af synspunkterne fra listen.",
          "V urder, om en mere lige fordeling af barsels- og forældreorloven mellem kvinder og mænd vil øge andelen af kvindelige topledere. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2019-sommer",
    "exam": {
      "year": 2019,
      "season": "Sommer",
      "label": "Maj-juni 2019"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en e-mail fra din ven Sofie, der arbejder som kommunikationsmedarbejder i et stort\nfirma. Hun er glad for jobbet, men hun arbejder meget. Hun skriverr blandt andet:\n\nTak for sidst, det var meget hyggeligt at have besøg af dig. Og hvor lyder det\nspændende, at du har meldt dig til maraton i Berlin næste år. Hvordan går det med\ntræningen?\nSom vi talte om, er jeg meget glad for mit nye job. Men jeg arbejder over 40 timer\nom ugen, og nu har min chef spurgt, om jeg vil være projektleder på et nyt projekt.\nDet er en stor chance for mig, men det betyder også mere overarbejde, så jeg ved\nikke, om jeg skal sige ja. Hvad synes du, jeg skal gøre?\nJeg vil også lige høre, hvordan du synes, det er at tage toget til arbejde hver dag?\nJeg er nemlig så træt af at sidde i kø på motorvejen hver dag – og måske kunne jeg\nundvære bilen.\nAngående det sommerhus på Bornholm, som vi snakkede om at leje, så kunne vi\nmåske leje det en uge i juli. Hvad siger du til det? ...",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes og snakker mere om jeres ferieplaner."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Kviklån",
        "situation": "Delprøve 2A",
        "context": "2A: Kviklån\nAndel af befolkningen der optager kviklån – fordelt på erhvervsmæssig status.\nAndel af befolkningen der optager kviklån – fordelt på erhvervsmæssig status.\nAsbjørn Nybo 28/6/2018 15.11\nKommentar [1]: Søjle 1 skal være en anelse\n14%\nhøjere.\n12%\n10%\n8%\n6%\n4%\n2%\n0%\nI arbejde Arbejdsløse På pension eller\nsygedagpenge\nKilde: https://www.kfst.dk/media/2779/20150701-markedet-for-kviklaan-opdateret-juli-2015.pdf\nKilde: https://www.kfst.dk/media/2779/20150701-markedet-for-kviklaan-opdateret-juli-2015.pdf",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet. kviklån. Vurder, om det er statens ansvar at begrænse de private lånefirmaers muligheder for",
          "Fortæl, hvilke årsager der kan være til en eller flere af de forskelle, diagrammet viser. at tilbyde forbrugerne kviklån.",
          "I 2017 blev det ved lov vedtaget, at der skal gå 48 timer, før en borger kan få udbetalt et kviklån. Vurder, Begrund dine synspunkter. om de(tB eers svtaarteenlsse nan asfv dare tatet bpeugnrkæt nsskea ld ued pgrøivrea tcea l.å 5n0e f%irm aaf edresn m suamliglehdeed ebre fsovra raet ltsielb).y de forbrugerne kviklån. Begrund dine synspunkter. Delprøve 2 D1 Kuv iskklaånl sekr rlåivn,e m manin kiamn utamge 2hu0r0ti gotr vdi.a private lånefirmaer. Kviklån skal normalt betales tilbage indenfor få måneder og har relativt høje renter. 1 Kviklån er lån, man kan tage hurtigt via private lånefirmaer. Kviklån skal normalt betales tilbage indenfor få måneder og har relativt høje renter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Uro i timerne i folkeskolen",
        "situation": "Delprøve 2B",
        "context": "Der er mange, der mener, at der er for meget uro i timerne i folkeskolen, og at det går ud over børnenes\nlæring. Der er forskellige holdninger til, hvordan man kan skabe mere ro i timerne.\nHer er der nogle synspunkter:\n• Mere af undervisningen skal foregå udenfor klasselokalerne.\n• Eleverne skal være med til at bestemme indholdet i undervisningen.\n• Der skal være mere udenadslære.\n• Lærerne skal sende urolige elever uden for døren.\n• Lærerne skal uddannes bedre i at skabe respekt.\n• Urolige elever skal gå i mindre klasser med andre urolige elever.",
        "bullets": [
          "Fortæl kort om dine egne erfaringer med uro i timerne, da du gik i skole.",
          "Kommentér et eller to af synspunkterne fra listen.",
          "V urder, om det er forældrenes, lærernes eller skolens ansvar at skabe mere ro i timerne i folkeskolen. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2019-vinter",
    "exam": {
      "year": 2019,
      "season": "Vinter",
      "label": "November-december 2019"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra dine venner, som har en datter, der går i gymnasiet. Datteren er blevet tilbudt\nat flytte i en lejlighed sammen med en veninde. Dine venner er usikre på, om det er en god ide. En\ndel af mailen står nedenfor.\n\nDu fortalte sidst, vi var sammen, at du ville tage på en længere rejse her til som-\nmer. Hvor har du besluttet at rejse hen?\nVi ved endnu ikke, om vi vil rejse her til sommer, fordi Maria som nævnt måske skal\nflytte. Og hvis hun flytter, får vi travlt med at hjælpe hende. Men vi er lidt bekymre-\nde for, om Maria er for ung til at flytte hjemmefra. Du kender hende jo rigtig godt.\nHvad tænker du?\nDer er også det med økonomien. Marias del af huslejen vil være 2.300 kr., og hun\nkan kun klare huslejen, hvis hun arbejder mere, end hun allerede gør nu. Tror du,\ndet er muligt at arbejde mere end 10 timer om ugen, når man samtidig går i gym-\nnasiet?\nHvis Maria flytter hjemmefra, så ser vi hende ikke mere til hverdag. Hvordan tror\ndu, det vil være for os – og for hende?...",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Flyrejser",
        "situation": "Delprøve 2A",
        "context": "Personer, der rejser ud fra større offentlige lufthavne i Danmark.\nFolk, der rejser ud fra større offentlige lufthavne i Danmark.\nMillioner 20\nUdenrigstrafik\nIndenrigstrafik\n2009 2010 2011 2012 2013 2014 2015 2016 2017\nKilde: Danmarks statistik, 2018\nKilde: Danmarks statistik, 2018",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til den udvikling, diagrammet viser. Begrund dine synspunkter.",
          "Vurder fordele og ulemper ved, at folk rejser mere end tidligere. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Gennemførelse og frafald på de videregående uddannelser",
        "situation": "Delprøve 2B",
        "context": "Hvert år begynder mange unge på en videregående uddannelse. De fleste gennemfører uddannelsen, men\nder er også en del, der dropper ud. Risikoen for at droppe ud er større for unge med lavt uddannede\nforældre.\nHer er nogle forslag til, hvordan man kan få flere unge til at gennemføre en uddannelse.\n• Bedre vejledning før uddannelsesvalg.\n• Flere undervisningstimer på uddannelsen.\n• Flere sociale arrangementer på uddannelsen.\n• Højere krav til karaktergennemsnit ved optagelse.\n• Brugerbetaling i uddannelsessystemet.\n• Mere individuel feedback fra underviserne.",
        "bullets": [
          "Fortæl kort, hvilke udfordringer du mener, der kan være, når man starter på en uddannelse.",
          "Kommentér et eller to af forslagene fra listen.",
          "Vurder, hvorfor en større andel af unge med veluddannede forældre end unge med forældre med en kort uddannelse gennemfører en videregående uddannelse. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2020-sommer",
    "exam": {
      "year": 2020,
      "season": "Sommer",
      "label": "Maj-juni 2020"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din danske ven, Christina. Hun har en ungarsk kæreste, Laszlo, der lige er\nstartet på en sprogskole. Christina skriver blandt andet:\n\nHvor er det utroligt, at du snart er færdig med sprogskolen. Tror du, du kommer\ntil at savne skolen?\nDet er altså lidt svært med det danske sprog for Laszlo. Han har ikke så mange\ntimer på sprogskolen, og vi taler mest engelsk sammen herhjemme. Har du nogen\nidéer til, hvad vi kan gøre, så Laszlo hurtigere lærer dansk?\nLaszlo kender heller ikke så mange danskere endnu, han kan tale dansk med. Hvad\ngjorde du egentlig for at få nogle danske venner?\nOg så glæder jeg mig til at ses næste weekend. Hvad synes du, vi skal lave? …",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå en aktivitet, I kan lave i næste weekend."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Stress",
        "situation": "Delprøve 2A",
        "context": "Andelen af danskere, som føler sig stressede i dagligdagen fordelt efter alder og køn.\nKilde: Statens Institut for Folkesundhed, 2017",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til den udvikling, diagrammet viser.",
          "Diskuter, om de sociale medier er en større stressfaktor end arbejdslivet. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Det første job som nyuddannet",
        "situation": "Delprøve 2B",
        "context": "Hvert år er der mange nyuddannede fra universiteter, professionshøjskoler og andre uddannelsessteder, der\nskal have deres første job som færdiguddannede. Der er forskellige forhold udover uddannelsen, der kan\nhave indflydelse på nyuddannedes jobmuligheder.\nHer er der nogle eksempler:\n• Frivilligt arbejde\n• Sprogkundskaber\n• Alder\n• Personligt netværk\n• Studiejob\n• Udlandsophold",
        "bullets": [
          "Fortæl kort om, hvordan du eller en anden, du kender, fik det første job som nyuddannet.",
          "Kommentér et eller to af eksemplerne fra listen.",
          "Diskuter, om personlighed er vigtigere end eksamensresultater, når man skal have et job som nyud- dannet. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2020-vinter",
    "exam": {
      "year": 2020,
      "season": "Vinter",
      "label": "November-december 2020"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din danske ven Trine. Hendes datter Rikke er 19 år, og hun blev student i\nsommer. En del af mailen står nedenfor.\n\nHvor er det dejligt, at vi snart har juleferie. Har du nogen planer?\nRikke blev jo student i sommer, men hun ved ikke rigtigt, hvilken uddannelse hun\nskal vælge. Lige nu arbejder hun for at tjene penge til at rejse. Jeg er dog nervøs\nfor, at hun mister interessen for at studere, hvis hun ikke snart kommer i gang.\nHvad tror du, det vil betyde for hendes motivation for at studere, hvis hun venter et\når mere?\nRikke vil gerne flytte hjemmefra og leder nu efter en bolig sammen med to af sine\nvenner. Jeg er ikke sikker på, om det er en god ide, at hun flytter hjemmefra, før\nhun har mere styr på sine fremtidsplaner. Hvad mener du?\nJeg trænger virkelig til ferie efter et travlt efterår på arbejdet. Vi overvejer faktisk\nat tage ud at rejse i julen i år, men vil på den anden side også gerne se familie og\nvenner i julen. Hvad synes du, vi skal gøre? ...",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes og snakker videre om Rikkes planer."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "At arbejde hjemmefra",
        "situation": "Delprøve 2A",
        "context": "Andelen af danskere med forskellig uddannelsesbaggrund, der i en undersøgelse fra 2017 svarede,\nat de havde arbejdet hjemmefra inden for de seneste 4 uger.\nAt arbejde hjemmefra\n70%\n60%\n50%\n40%\n30%\n20%\n10%\n0%\nGrundskole Erhvervsuddannelse Lang videregående\nuddannelse og phd.\nKilde: Danmarks Statistik (2017)",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til de forskelle, diagrammet viser.",
          "Vurdér, om det øger eller mindsker risikoen for stress, at man har mulighed for at arbejde hjemmefra. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Personalegoder",
        "situation": "Delprøve 2B",
        "context": "Mange virksomheder tilbyder deres medarbejdere personalegoder for at tiltrække og fastholde dem i virk-\nsomheden. Her er nogle eksempler på personalegoder:\n• Sociale arrangementer i fritiden\n• Børnepasning på virksomheden\n• Efteruddannelse og kurser\n• Fitness-abonnement\n• Sundhedstjek på arbejdspladsen\n• Kantinemad med hjem",
        "bullets": [
          "Fortæl kort om personalegoder, du selv har fået eller har hørt om.",
          "Kommentér et eller to af eksemplerne fra listen.",
          "Vurdér, om det er vigtigt for arbejdsmiljøet, at en virksomhed tilbyder deres medarbejdere personalegoder. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2021-sommer",
    "exam": {
      "year": 2021,
      "season": "Sommer",
      "label": "Maj-juni 2021"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra Lise, som er din gode veninde. Lise bor i et hus i Odense sammen med sin\nmand. Hendes søster skal skilles.\neee\n\nTak for sidst, det var hyggeligt at se dig. Jeg er spændt på at høre, om du så\nhar købt den elcykel, du snakkede om?\nMin søster Nina, som du måske kan huske, skal skilles. Hun har fundet en lejlighed,\nsom hun kan overtage om en måned. Hun har spurgt, om hun må flytte ind hos\nos med sine to børn, mens hun venter på, at lejligheden bliver klar. Men måske er\ndet bedre, de venter og flytter direkte ind i lejligheden. Hvad tror du er bedst?\nJeg har tænkt meget på, at vi altid godt har kunnet lide min søsters mand. Men\nnu er jeg bange for, om vi kan blive ved med at se ham fremover. Hvad tror du?\nJeg glæder mig til at høre fra dig og høre om, hvordan det går med at lære\ndansk. Jeg har hørt, at du snart er færdig med sprogskolen.",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes, så du kan fortælle om, hvordan det går med at tale dansk."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Jobomsætning",
        "situation": "Delprøve 2A",
        "context": "Jobomsætning i Danmark i 2018 fordelt på alder\nAntal\npersoner\n20-34-årige 35-49-årige 50-64-årige\n■ ■ ■\nKilde: www.jobindsats.dk, 2020",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til de forskelle, diagrammet viser.",
          "Vurdér fordele og ulemper for en virksomhed ved, at der sker en udskiftning blandt medarbejderne. * Jobomsætning = antal personer, der starter i et nyt job fra et andet job, fra ledighed eller som nyuddannet."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Unge og sundhed",
        "situation": "Delprøve 2B",
        "context": "Nogle unge har en usund livsstil, hvor de bevæger sig for lidt, spiser og drikker for usundt og ofte også\nryger.\nHer er der nogle forslag til, hvordan unge kan få en sundere livsstil:\n• Højere aldersgrænse for køb af alkohol\n• Madordninger med sund mad på skoler og ungdomsuddannelser\n• Forbud mod reklamer for slik og sodavand\n• Mere undervisning i sundhed og livsstil i folkeskolen\n• Flere idrætstimer på skoler og ungdomsuddannelser\n• Obligatoriske samtaler med egen læge om sund livsstil",
        "bullets": [
          "Fortæl kort om, hvordan du selv prøver at leve sundt.",
          "Kommentér et eller to af eksemplerne fra listen.",
          "Vurdér, om venner og ungdomskultur har større indflydelse på unges livsstil end forældrene. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2021-vinter",
    "exam": {
      "year": 2021,
      "season": "Vinter",
      "label": "November-december 2021"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din ven Erik. Han har lige fået tilbud om et job i sit firmas hovedkontor, der\nligger i en anden by i Danmark.\n\nTak for sidst, det var hyggeligt. Jeg er spændt på at høre om den kon-\ncert, du skulle til. Hvordan var den så?\nSom jeg fortalte, har min chef tilbudt mig et job i hovedkontoret. Det er en\nspændende udfordring, og jeg har sagt ja. I det nye job bliver jeg leder for\nnogle af mine nuværende kolleger. Tror du, det bliver svært?\nJeg får også nogle længere arbejdsdage. Hvad tror du, det kommer til at\nbetyde for familielivet?\nHovedkvarteret ligger jo ikke her i byen, så der er for langt at cykle på\narbejde. Spørgsmålet er, om jeg skal tage bilen eller toget. Hvad ville du\ngøre?",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes og snakker videre om din vens situation."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Sygefravær",
        "situation": "Delprøve 2A",
        "context": "Gennemsnitligt sygefravær i procent inden for fire typer job\n8%\n7%\n6%\n5%\n4%\n3%\n2%\n1%\n0%\nLedere Forskere ved Sygeplejersker Social- og\nuniversiteter sundhedsassistenter\nKilde: Fraværsrapport 2019. Det Nationale Forskningscenter for Arbejdsmiljø, 2019.",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til nogle af de forskelle, diagrammet viser.",
          "Vurdér, om det er ledelsens eller medarbejdernes eget ansvar at nedbringe sygefraværet. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Klimaforandringer og ansvar",
        "situation": "Delprøve 2B",
        "context": "Der tales meget om, at de klimaforandringer, vi oplever nu med ekstremt vejr, oversvømmelser og tørke,\nvil blive endnu værre i fremtiden, hvis ikke vi nedbringer udledningen af CO .\nHer er der nogle forslag til, hvad den enkelte selv kan gøre for at nedbringe CO -udledningen:\n• Undlade at rejse med fly\n• Sortere affaldet\n• Tage cyklen eller gå til arbejde eller skole\n• Undlade at købe plastikprodukter\n• Købe genbrugstøj\n• Spise plantebaseret",
        "bullets": [
          "Fortæl kort om noget, du har oplevet eller hørt om, der er påvirket af klimaforandringer.",
          "Kommenter et eller to af forslagene fra listen.",
          "Vurder, om det er den enkeltes eller samfundets ansvar at nedbringe udledningen af CO . Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2022-sommer",
    "exam": {
      "year": 2022,
      "season": "Sommer",
      "label": "Maj-juni 2022"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din danske ven Mia. Hun har været udstationeret i New York i tre år for et\ndansk firma, og nu skal hun snart hjem til Odense sammen med sin familie.\n\nTak for snakken i sidste uge, det var hyggeligt at tale med dig på Skype.\nJeg er meget spændt på at høre om din køreprøve. Hvordan gik det?\nSom du ved, er vores tid i New York snart slut, og vi skal hjem til Odense\nom tre uger. Jeg skal arbejde sammen med nogle kolleger, jeg ikke kender.\nHvad synes du, jeg skal gøre for at få en god start på arbejdet?\nBørnene er jo blevet teenagere, og de er meget kede af at sige farvel til\nderes venner her i New York. Jeg er spændt på, om de kan holde kontakten.\nTror du, det er muligt?\nJens har fået nyt arbejde i Danmark, som han glæder sig til at komme i\ngang med efter 3 år som hjemmegående. Det nye job ligger dog 30 km fra\nOdense, så vi overvejer at købe en ekstra bil, men han kan også tage toget.\nHvad ville du gøre?",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes, når Mia kommer hjem."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Klimabekymring og alder",
        "situation": "Delprøve 2A",
        "context": "Andel personer i forskellige aldersgrupper, der er meget bekymrede over klimaforandringer\n30%\n25%\n20%\n15%\n10%\n5%\n0%\n18-34 år 35-49 år 50-70 år Alle\nUndersøgelsen er foretaget blandt et repræsentativt udvalg på 2.000 personer i alderen 18-70 år.\nKilde: https://ida.dk",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til de forskelle, diagrammet viser.",
          "Hvilke fordele og ulemper mener du, der kan være for samfundet ved, at unge bekymrer sig om klimaforandringerne? Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "En attraktiv arbejdsplads",
        "situation": "Delprøve 2B",
        "context": "Der er forskellige faktorer, der kan have betydning for, hvor attraktiv en arbejdsplads er for medarbejderne.\nHer er nogle eksempler:\n• Godt samarbejde mellem kolleger\n• Fleksible arbejdstider\n• Indflydelse på egne arbejdsopgaver\n• God løn\n• Mulighed for efteruddannelse\n• Personalegoder",
        "bullets": [
          "Fortæl kort om en attraktiv arbejdsplads, du har været på eller har hørt om.",
          "Kommentér en eller to af faktorerne fra listen.",
          "Vurdér, om det er lederens personlige kvalifikationer eller faglige kvalifikationer, der er vigtigst for, om en arbejdsplads er attraktiv."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2022-vinter",
    "exam": {
      "year": 2022,
      "season": "Vinter",
      "label": "November-december 2022"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din gode ven Claus, der for nylig har fået et nyt job.\n\nTak for sidst. Jeg håber, du havde en god ferie. Hvordan var det så at\nvandre i bjergene?\nJeg er rigtig glad for mit nye job. Jeg har dog det problem, at der er meget\nlarm på kontoret, hvor jeg arbejder. Vi sidder over 20 personer i samme\nrum, og især to af mine kolleger snakker meget sammen. Jeg overvejer at\nsige til dem, at det forstyrrer mig. Synes du, jeg skal gøre det?\nMange af mine nye kolleger bliver tit en time eller to efter arbejde om\nfredagen og drikker en øl eller sodavand. Jeg vil egentlig helst bare hjem\nog holde weekend. Tror du, det er vigtigt, at jeg alligevel bliver?\nVi skal jo snart til Steens 30-års fødselsdag og har aftalt at give en gave\nsammen. Men hvad skal vi egentlig give ham? …",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes, så du kan høre mere om Claus, nye job."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Udenlandsk arbejdskraft i Danmark",
        "situation": "Delprøve 2A",
        "context": "Antal udenlandske statsborgere med lønindkomst i Danmark\n2012 2013 2014 2015 2016 2017 2018 2019 2020\nAntal personer\nKilde: www.jobindsats.dk",
        "bullets": [
          "Beskriv kort, hvad diagrammet viser.",
          "Fortæl, hvilke årsager der kan være til den udvikling, diagrammet viser?",
          "Vurdér, hvad udenlandsk arbejdskraft vil betyde for det danske samfund i fremtiden. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Trivsel på arbejdspladsen",
        "situation": "Delprøve 2B",
        "context": "Der er forskellige faktorer, der kan påvirke trivslen enten positivt eller negativt på en arbejdsplads.\nHer er nogle eksempler:\n• Mulighed for at arbejde hjemmefra\n• Mulighed for at gøre karriere\n• Mulighed for at få bonus\n• Ledelsesstil\n• Omorganisering i virksomheden\n• Sikkerhed i ansættelsen",
        "bullets": [
          "Fortæl kort om et arbejde, som du, eller én du kender, har været glad for.",
          "Kommenter én eller to af faktorerne fra listen.",
          "Vurdér, om gode kolleger eller udfordrende arbejdsopgaver er vigtigst for, om man trives på en arbejdsplads. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2023-sommer",
    "exam": {
      "year": 2023,
      "season": "Sommer",
      "label": "Maj-juni 2023"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din danske ven, der snart skal være forælder.\n\nTak for sidst, det var hyggeligt at mødes med dig. Du sagde, at du leder\nefter et nyt sted at bo. Hvordan går det med det?\nSom sagt, så glæder vi os til, at vi til vinter skal være forældre for første\ngang . Vi har stadig ikke besluttet, om vi vil have barnets køn at vide før\nfødslen. Synes du, man skal vide på forhånd, om det bliver en pige eller en\ndreng?\nVi har snakket om, at vi vil tage en måneds forældreorlov sammen og så\nrejse en tur ud i verden med den lille ny. Synes du ikke, det lyder som en\ngod idé?\nDu var jo med os på ferie sidste år, og det var så hyggeligt. I år tager vi en\nuge op i mine forældres sommerhus i slutningen af juli.\nVil du med? …",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes inden længe og taler om sommerferien."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Trafiksikkerhed",
        "situation": "Delprøve 2A",
        "context": "Andel af dræbte og tilskadekomne i trafikken\nAlder\nDræbte og\n75+ tilskadekomne\nAndel af\n65-74 befolkningen\n55-64\n45-54\n35-44\n25-34\n18-24\n15-17\n0-14\n0 5 % 10 % 15% 20 %\nKilde: https://www.vejdirektoratet.dk/sites/default/files/2020-10/Politikredsrapport_2019.pdf",
        "bullets": [
          "Beskriv hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til nogle af de forskelle, diagrammet viser.",
          "Vurdér, hvad staten og kommunerne kan gøre for at reducere antallet af dræbte og tilskadekomne i trafikken. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Sundhedstilbud på arbejdspladsen",
        "situation": "Delprøve 2B",
        "context": "Mange arbejdspladser i Danmark tilbyder aktiviteter, der skal få deres ansatte til at leve sundere. Nogle til-\nbud indgår i arbejdstiden, og andre foregår i fritiden.\nHer er nogle eksempler:\n• Pauser med gymnastik i arbejdstiden\n• Oplæg om sund livsstil i arbejdstiden\n• Sundhedstjek i arbejdstiden\n• Løbeklub efter arbejdstid\n• Tilskud til motionsaktiviteter i fritiden\n• Kurser i rygestop i fritiden",
        "bullets": [
          "Fortæl kort om sundhedstilbud på en arbejdsplads, du kender eller har hørt om.",
          "Kommenter ét eller to af eksemplerne fra listen.",
          "Vurdér fordele og ulemper ved, at en arbejdsplads engagerer sig i sine medarbejderes livsstil. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2023-vinter",
    "exam": {
      "year": 2023,
      "season": "Vinter",
      "label": "November-december 2023"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din ven, Hanne, som har en søn, der går på erhvervsskole.\n\nDu snakkede om sidst, at I skulle have nyt køkken. Hvordan er det\nblevet?\nMathias er jo i gang med at uddanne sig til elektriker. Han får derfor\nskiftevis SU og lærlingeløn, mens han tager sin uddannelse. Synes du,\nhan burde betale husleje for at bo herhjemme?\nJeg vil egentlig gerne opfordre ham til at læse videre til ingeniør. Tror du,\ndet er en dårlig idé, at jeg blander mig?\nVi plejer jo at tage til Italien i sommerferien. Men Mathias har jo fået en\nkæreste, som han nu har haft i et halvt års tid. Synes du, vi skal invitere\nhende med? …",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I mødes inden længe og taler om sommerferien."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Mænds og kvinders valg af erhvervsuddannelser",
        "situation": "Delprøve 2A",
        "context": "Andelen af mænd og kvinder optaget på erhvervsuddannelser fordelt efter uddannelsesområde i 2021.",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til nogle af de forskelle, diagrammet viser.",
          "Vurdér, om den nuværende kønsfordeling på erhvervsuddannelserne er et problem for det danske samfund. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Valg af transportform",
        "situation": "Delprøve 2B",
        "context": "Der er forskel på, hvad folk lægger vægt på, når de vælger transportform til og fra arbejde.\nHer er nogle eksempler:\n• Det skal være billigt\n• Det skal være hurtigt\n• Det skal være komfortabelt\n• Det skal give motion\n• Det skal være muligt at arbejde under transporten\n• Det skal være miljøvenligt",
        "bullets": [
          "Fortæl kort om dit valg af transportform.",
          "Kommentér et eller to af eksemplerne fra listen.",
          "Vurdér fordele og ulemper for samfundet ved, at personer, der har mere end 24 km til og fra arbejde, kan få kørselsfradrag.1 1 Kørselsfradrag er det beløb, der kan trækkes fra en persons indkomst, før skatten beregnes. Man kan få kørselsfradrag, hvis man har mere end 24 km til og fra arbejde."
        ],
        "minWords": 200
      }
    ]
  },
  {
    "id": "pd3-2024-sommer",
    "exam": {
      "year": 2024,
      "season": "Sommer",
      "label": "Maj-juni 2024"
    },
    "tasks": [
      {
        "id": "email",
        "key": "email",
        "title": "En e-mail",
        "situation": "Du har fået en mail fra din danske ven, der lige har fået nyt arbejde og er flyttet til en anden by.\n\nTak for sidst, det var hyggeligt. Du sagde, at du snart er færdig med din\ndanskuddannelse, men at du ikke føler, du er god nok til dansk. Har du\ntænkt mere over, hvad du nu vil gøre?\nJeg kender endnu ikke så mange her i byen, men mange af mine kolleger\nbor heromkring, og de er egentlig rigtig søde. Tror du, det vil være en god\nidé at invitere dem alle sammen hjem til mig en aften?\nOg så noget helt andet. På min nye arbejdsplads er der kage til både møder\nog fødselsdage, og det synes jeg simpelthen bliver for meget. Synes du, jeg\nskal foreslå, at vi dropper kagen til møderne?\nOg så har jeg lige et praktisk spørgsmål til dig. Jeg har jo stadig en del af\nmine ting stående i kælderen under min gamle lejlighed. De skal flyttes\nherover. Har du mulighed for at hjælpe mig med det i weekenden? …",
        "bullets": [
          "Tak for mailen.",
          "Kom ind på de understregede dele i mailen.",
          "Foreslå, at I ringer sammen og snakker videre."
        ],
        "minWords": 100
      },
      {
        "id": "essay-a",
        "key": "essay-a",
        "title": "Frivilligt arbejde",
        "situation": "Delprøve 2A",
        "context": "Andelen af den voksne danske befolkning, som udførte frivilligt arbejde i 2020 inden for udvalgte områder.\n15%\n10%\n5%\n0%\nKulturområdet (fx museer)\nIdrætsområdet (fx sportsklubber)\nDet sociale område (fx besøgsvenner og flygtningevenner)\nMiljøområdet (fx naturfredning)\nSundheds- og sygdomsområdet (fx bloddonor og pa(cid:30)en(cid:29)orening)\nKilde: Frivillighedsundersøgelsen 2020, side 27, https://www.vive.dk/media/pure/16186/5662919",
        "bullets": [
          "Beskriv kort hovedtrækkene i diagrammet.",
          "Fortæl, hvilke årsager der kan være til nogle af de forskelle, diagrammet viser.",
          "Vurdér, om man kan løse manglen på sygeplejersker og social- og sundhedsassistenter ved hjælp af frivillig arbejdskraft. Begrund dine synspunkter."
        ],
        "minWords": 200
      },
      {
        "id": "essay-b",
        "key": "essay-b",
        "title": "Lønforskelle og lønniveauer",
        "situation": "Delprøve 2B",
        "context": "Der er forskel på, hvad folk i forskellige erhverv og med forskellige uddannelsesbaggrunde og erfaringer\ntjener. Det er der forskellige holdninger til.\nNogle mener, at én eller flere af nedenstående grupper får for lidt i løn:\n• Ansatte, der passer børn, syge og ældre\n• Ansatte med fysisk hårdt arbejde\n• Ansatte med skæve arbejdstider, fx natarbejde\n• Højtuddannede\n• Topledere\n• Kvinder",
        "bullets": [
          "Fortæl kort om nogle lønforskelle, du kender til.",
          "Kommenter én eller to af holdningerne fra listen.",
          "Vurdér fordele og ulemper for det danske samfund ved, at der er relativt små lønforskelle mellem højt- lønnede og lavtlønnede. Begrund dine synspunkter."
        ],
        "minWords": 200
      }
    ]
  }
]
